board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    # path('<int:pk>/update/', views.update, name='update'),
    path('<int:board_pk>/edit/', views.edit, name='edit'), # GET(edit), POST로 들어오면 (UPDATE)
    path('<int:board_pk>/delete/', views.delete, name='delete'), # POST(DELETE)
    path('<int:board_pk>/', views.detail, name='detail'),
    # path('create/', views.create, name='create'),
    path('new/', views.new, name='new'), # GET(NEW) 유저가 post 이면 써지는 요청이고 , new 는 띄워주는거구나 / POST(CREATE)
    path('', views.index, name='index'),
    ]
    

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('board/', include('board.urls')),
    path('admin/', admin.site.urls),
]

board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return f"{self.id}:{self.title}"
        return self.title

class Comment(models.Model):
    # 참조하는 부모객체를 소문자로 주로 씀, 첫번째 객체는 부모객체
    board = models.ForeignKey(Board, on_delete=models.CASCADE) # foreignkey 필수인자, 게시물이 지워졌을 때, 그 아래 달린 댓글들을 어떻게 할 것인가
    #참조하는 부모객체가 사라졌을 때, 부모에 딸려있는 자식 객체들을 어떻게 처리할지 정의한다
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    def __str__(self):
        return self.content

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment
# from pprint import pprint
# Create your views here.
def index(request):
    # pprint(request)
    # pprint(type(request))
    # pprint(dir(request))
    # pprint(request.scheme) # http
    # pprint(request.get_host)
    # pprint(request.get_full_path())
    # pprint(request.build_absolute_uri())
    # pprint(request.META) # 에러 페이지 떴을 때 딕셔너리
    # pprint(request.method)
    
    
    boards = Board.objects.order_by('-pk')
    context = {
        'boards': boards,
    }
    return render(request,'board/index.html', context)
    
def new(request):
    if request.method == 'POST':
        #CREATE
        title = request.POST.get('title')
        content = request.POST.get('content')
        
        board = Board(title=title, content=content)
        board.save()
        
        # return redirect(f'/board/{board.pk}/')
        return redirect(f'board:detail', board.pk)
    else:
        return render(request, 'board/new.html')
    

def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    
    context = {
        'board' : board,
        'comments' : comments,
    }
    return render(request,'board/detail.html', context)
    
def delete(request,board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        
        board.delete()
    # return redirect('/board/')
        return redirect('board:index')
    else:
        return redirect('board:detail', board.pk)
    # 포스트 방식으로만 삭제할 수 있게
    
    
def edit(request, board_pk):
    if request.method == 'POST':
        # UPDATE
        board = Board.objects.get(pk=board_pk)
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.save()
        # return redirect(f'/board/{ board.pk }/')
        return redirect(f'board:detail', board.pk)
    else:#EDIT
        board = Board.objects.get(pk=board_pk)
        return render(request, 'board/edit.html', {'board': board})



# 댓글 함수들 


def comments_create(request,board_pk):
    # 댓글을 달 게시물 가지고오기
    board = Board.objects.get(pk = board_pk)
    # form 에서 넘어온 comment data
    content = request.POST.get('content')
    
    # 댓글 생성 및 저장
    # board에 board 전체 객체를 집어넣으면, 지가 알아서 빼냄
    # orm은 객체를 넣어야 함
    comment = Comment(board=board, content = content)
    comment.save()
    return redirect('board:detail', board.pk)
    
def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk = comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect(f'board:detail', board_pk)
    else:
        return redirect(f'board:detail', board_pk)

board/templates/board/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        
   {% block body %}
    {% endblock %}
        
    </div>
 
 
 
 
 
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/detail.html
{% extends 'board/base.html' %}
   {% block body %}
   <h1>DETAIL</h1>

   <hr>
       <h2>{{ board.id }} 번 째 글</h2>
       <hr>
       <p>{{ board.title }}</p>
       <p>{{ board.content }}</p>
       <p>{{ board.created_at }}</p>
       <p>{{ board.updated_at }}</p>
        <a href="{% url 'board:index' %}">[BACK]</a>
        <!--board라는 앱의 edit-->
        <a href="{% url 'board:edit' board.pk %}">[수정]</a>
        <!--<a href="/board/{{ board.pk }}/edit/">[수정]</a>-->
        <!--<a href="{% url 'board:delete' board.pk %}" onclick="return confirm('R U SURE?')">[삭제]</a>-->
        <!--버튼 자체를 form으로 바꾸기-->
        <form action='{% url 'board:delete' board.pk %}' method='POST' style='display: inline'onsubmit="return confirm('R U SURE?');">
            {% csrf_token %}
            <input type="submit" value="[삭제]"/>
        </form>
        <!--<a href="/board/{{ board.pk }}/delete/" onclick="return confirm('R U SURE?')">[삭제]</a>-->
        <hr>
        {% for comment in comments %}
        <li>
            {{ comment.content }}
            <form action="{% url 'board:comments_delete' board.pk comment.pk %}"method='POST' onsubmit="return confirm('r u sure?');" style='display:inline'>
                {% csrf_token %}
                <input type="submit" value="삭제"/>
            </form>
            </li>
            <!--비어있을 때 조건을 주는 방법-->
        {% empty %}
        <p><b>댓글이 없어욤</b></p>
        {% endfor %}
        <hr>
        <p>댓글작성/ {{ comments | length }} 개의 댓글 </p>
        #댓글 작성하는 곳으로 보내기
        <form action='{% url 'board:comments_create' board.pk %}' method='POST'>
            {% csrf_token %}
            comment : <input type="text" name="content"/>
            <input type="submit" name="sublit"/>
        </form>
        
    {% endblock %}

board/templates/board/edit.html
{% extends 'board/base.html' %}
   {% block body %}
   <h1>EDIT</h1>
   <!--<form action="/board/{{ board.pk }}/update/" method="POST">-->
   <form action="{% url 'board:edit' board.pk %}" method="POST">
    <!--여기도 action 지워도 됨-->
       {% csrf_token %}
       <label for="title" >TITLE</label>
       <input type="text" id='title' name="title" value="{{ board.title }}"/>
       <label for="content">CONTENT</label>
       <input type="text" id='content'name="content" value="{{ board.content }}"/>
       <input type="submit" name="제출"/>
   </form>
   <a href="/board/"> [BACK]</a>
    {% endblock %}
    

board/templates/board/index.html
{% extends 'board/base.html' %}
   {% block body %}
   <h1>Index</h1>
   <!--<a href="/board/new/">[새글작성하기]</a>-->
   <a href="{% url 'board:new' %}">[새글작성하기]</a>
   <hr>
   {% for board in boards %}
       <p>{{ board.pk }}</p>
       <p>{{ board.title }}</p>
       <p>{{ board.created_at | timesince }} 전 입니당</p>
        <!--<a href="/board/{{ board.pk }}">[글 보러 가기]</a>-->
        <a href="{% url 'board:detail' board.pk %}">[글 보러 가기]</a>
        <hr>
    {% endfor %}
    {% endblock %}
        

board/templates/board/new.html
{% extends 'board/base.html' %}
   {% block body %}
   <h1>NEW</h1>
   <form action="{% url 'board:new' %}" method="POST">
    <!--액션을 지워도 됨, 어차피 new의 위치에 와있었고 post 이니까 자신의 위치로 돌아감, 현재 위치로 요청이 감-->
       {% csrf_token %}
       <label for="title">TITLE</label>
       <input type="text" id='title' name="title"/>
       <label for="content">CONTENT</label>
       <input type="text" id='content'name="content"/>
       <input type="submit" name="제출"/>
   </form>
   <a href="/board/"> [BACK]</a>
   <a href="{% url 'board:index' %}"> [BACK]</a>
    {% endblock %}
    
<!--get으로 들어오면 일단 완성이 되고, 아 저 주소로 들어가야하는구나 하고 현재 자신의 위치로 돌아감  new 위치에서의 행동은 post 이니까 -->